heartbeat.monitors:
#Monitor all containers using an icmp ping
- type: icmp
  schedule: '*/5 * * * * * *'
  hosts: 
    - elasticsearch
    - kibana
    - logstash
  ipv4: true
  ipv6: true
  mode: any
  timeout: 16s
  wait: 1s
#Monitor the ES instance over http with a GET to the /  - checking for a 200 response
- type: http
  enabled: true
  schedule: '@every 5s'
  urls:
    - http://elasticsearch:9200
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'
  check.request:
    method: "GET"
  check.response:
    status: 200
#Monitor the Kibana instance with a http GET to / - checking for a 200 response code
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://kibana:5601/login"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200
#Monitor the Logstash instance with a http GET to / - checking for a 200 response code
- type: http
  enabled: true
  schedule: '@every 5s'
  urls: ["http://logstash:9600"]
  ipv4: true
  ipv6: true
  mode: any
  timeout: 5s
  check.request:
    method: "GET"
  check.response:
    status: 200

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'